---
deployment:
  tasks:
    - export DEPLOY_DIR=/home/genufyin/public_html/
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - rm -rf ~/${DEPLOY_DIR}/*
    - cp -r dist/* ~/${DEPLOY_DIR}/
